### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#108]
Obviously we don't yet have any FAQs. But foresee space somewhere for a future FAQ page.

**Comment by rsimon** [comment]
Just pinging the status on this one. Is the text ready to go?

**Comment by eltonteb** [comment]
I'm good with it, but @leifuss should probably review it again.

**Comment by rsimon** [comment]
A first version of the FAQ page is now live: http://recogito.pelagios.org/help/faq

As compared to the Google Doc, I shuffled the order around a bit. Also, I did not include some of the more general question that will be answered in the "Guide" section. 

I'm closing the issue since, technically, the page now exists. In terms of the content, the FAQ are a living document by definition, anyway. So do take a look, give feedback, add improvements, etc. (Pull requests welcome!)
