### ISSUE TITLE
Annotation Stats page

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#137]
Starting to gather ideas on what should be on the "Annotation Stats" page. (Starting point is the stats page on the old Recogito):
- List of contributing users (and number of contributions)
- Timeline of contribution activity?
- Rate of "completeness" (i.e. distribution of verification status values) as pie chart
- Flagged places (grouped by toponym)
- Aggregate information about georesolution: top places, grouped by gazetteer URI; "anomalies" (has the same toponym been assigned to different gazetteer URIs?)
- Some metric about auto-match performance?

**Comment by eltonteb** [comment]
I'm just thinking what other data might be useful to inspect as a user. Possibly:
- information about this user's activity: i.e. what other documents they've worked on (with stats)
- information about this document's relations: i.e. those documents most closely related to the current one in terms of places mentioned and georeferenced (perhaps also a chance to check "inter"-textual anomalies as well as the "intra"-textual ones mentioned above)

On a related point: if Recogito is now going to be decentralised (i.e. I have my own version and I would no longer have to log in to a central site, where I can see the other documents - as in Pelagios 3), how would I know whether my document (text or map) has been annotated before, particularly if it's a different version (a different edition or translation)? It would be helpful to know, e.g., whether Agathermus has been annotated before - but, if I didn't know of Chiara's work, how would I find out? Perhaps a correlation index of some sort? i.e. a pop up tells me after I've made so many annotations that there's "x" document which shows the same pattern?

**Comment by rsimon** [comment]
@eltonteb to your first point: something like that will be coming as part of the "profile page". I'd probably model it on the github profile pages. E.g. if you go to http://github.com/rsimon you'll see that activity chart. I'd like to have something similar in the header of the Recogito profile page (issue #89).

Regarding to the second point: I think that's a really good one. You wouldn't know about similar docs. And if the owner locked them to the public, I'd say you shouldn't. But if they are marked as publicly visible (which is a document setting that's implemented already), then a "similar docs" feature would indeed be interesting and useful. I agree it could fit into the stats page - since it would likely be based on similarities in terms of tagged places. How to implement... don't know that yet. But certainly something I'll keep in mind!

**Comment by ChiaraPalladino** [comment]
> information about this document's relations: i.e. those documents most closely related to the current one in terms of places mentioned and georeferenced (perhaps also a chance to check "inter"-textual anomalies as well as the "intra"-textual ones mentioned above)

I really like this suggestion as well. 
I think that we could try to overcome the problem of "secret" documents by establishing some "good annotation practice" (again...guidelines...). It would be desirable that people keep their documents close to the public only if they feel it is very necessary, e.g. if the document is particularly problematic, if it's part of a specific team project or if they feel it needs the intervention of an expert exclusively.

**Comment by eltonteb** [comment]
just one last series of point while I think about it, which isn't so much about annotation as about the document itself (but I'll post here since it's related). As a user (I must find a different way of putting this, since it makes me sound like a druggie...), I'd like to know:
- What is the edition of the document (This is particularly important for scholarly work)
- Where can I find the original document (ideally a CTS URN if available, but if not online then the conventional publisher and place of publication)
- Where can I find the annotated document (again, if that's available: I think it's important to distinguish between the two, since the latter - the annotated version - will be an enriched text, but also someone's interpretation)
- What's been annotated in it (i.e. only places, or also people, other spatial expressions, etc.?)
- How has it been annotated (ok, for our purposes everything is going to be Recogito'd, but: (i) there are (already) now 2 versions of this platform; and (ii) if we think of the broader ecosystem, I can see it being quite useful to know whether this or that document has been annotated using Recogito or by some other means (like the Perseus texts).

I'm not sure how useful any of this is, but these are things I'd like greater clarity and transparency about re. digital texts.

**Comment by rsimon** [comment]
I'll try to sort through that later. But most of this is not "stats", but simply metadata - which sits at a different page. Few things to keep in mind though to avoid misunderstanding: 

* people will upload __all sorts__ of things - not just stuff that is available at a CTS URI. 
* what do you mean by "where do I find the annotated document"? The annotated document would be in Recogito (or am I missing something?)
* Re "How" has it been annotated - through Recogito. I think you may be confusing materials in Recogito vs. things made accessible more generally, e.g. Peripleo.

**Comment by rsimon** [comment]
1. Agreed. Are you willing to draft an outline for this perhaps?

2. No. Recogito provides __personal workspaces__ now. I.e. you have your own account on Recogito, where you can only see the documents you uploaded yourself, and those that have been shared with you by others. Comparable to, say, GoogleDrive or GitHub. But there is still one central Recogito run by us (how else would we offer this to non-tech users?); but it's open source software, so anyone can set up their own instance, given they have a Webserver and basic knowledge on how to run it. 

Recogito has [clean URIs](https://en.wikipedia.org/wiki/Semantic_URL).

* Documents in Recogito get assigned a unique (within this Recogito instance) identifier; and every document generally consists of multiple parts. The URI for this is

http://{address of your Recogito server}/document/{id}/part/{part number}

followed by the "view" you want to see the document in. For example

http://recogito.pelagios.org/document/5wv49itvepiyjp/part/1/edit

* Same for the users' personal workspaces, where the workspace is generally available at

http::/{address of your Recogito server}/{your username}

E.g.

http://recogito.pelagios.org/rainer

Other areas of Recogito (user account settings etc.) follow the same principles of clean URI design.

3. As I said before, there are a number of "predefined metadata fields" which you see when you upload a document. Plus I'm thinking about the future option of adding additional "untyped fields", i.e. custom fields with any name, and any (text) content you want.

Finally, every document will also come with a discussion board. Perhaps that's also a place where issues can be discussed between doc owner, contributors, public.

**Comment by ChiaraPalladino** [comment]
Perhaps it's worth to make some metadata fields compulsory? 

I'd also like to see the source where the text has been taken from, as in v. 1. Therefore not just the edition of the document, but the actual link where it has been taken from, if there is any, or a declaration that the  Recogito version is personal work. It was a huge problem to find the source for some texts in v. 1, and in some cases we spotted mistakes.

**Comment by rsimon** [comment]
I think it's important to put as low a barrier to get started as possible. (@eltonteb: you'll remember that was one of Mia's key messages.) That's why only the title field is mandatory at the moment. But working on the assumption that Recogito is supposed to cater specifically for a scholarly audience, I could see a process where you'd be required to fill additional metadata fields before you're able to make a document public. (Perhaps people could drop in things like a BibTex citation etc.)

**Comment by rsimon** [comment]
In the spirit of re-using existing patterns (regarding metadata editing): how does e.g. Zotero handle this in the UI?

**Comment by rsimon** [comment]
Recogito now provides a framework for __stats plugins__, small bundles of JavaScript, CSS & a config file that allows 3rd parties to embed their own charts, visualizations, tables etc. into the stats pages.
