### ISSUE TITLE
'Learn More' tutorial

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#191]
We'll need something (and there's a dead link on the splash page already). I'd like it to be more visual than the old static tutorial at http://pelagios.org/recogito/documentation. Perhaps split across several thematic "lessons".

Eventually, something interactive (using one of the JS "tutorial" libraries) would be nice. But realistically that won't be feasible for us to complete in the given time/budget-frame.

**Comment by ChiaraPalladino** [comment]
Thumbs up for this. Maybe animated gifs are a good compromise? We could have a new Sunoikisis session with a video tutorial on Recogito 2 next year - that would be great.

**Comment by rsimon** [comment]
You mean you could hold a Sunoikisis video session which we could then re-use as an online tutorial? A fantastic idea!

Next year sounds good. Should we open a GoogleDoc or something to do some advance planning at some point?

**Comment by ChiaraPalladino** [comment]
We will have a sunoikisis planning meeting in December and it should be pretty easy to set up a session on Recogito. We generally start writing google docs to plan the syllabus before each session, after the planning meeting is over.

**Comment by rsimon** [comment]
Sounds like a plan! :-)

**Comment by rsimon** [comment]
Issue #245 has added a "Welcome to Recogito" document. After signing up for a new account, this text document automatically appears on the personal start page, so that first time users have something to play around with. Certainly not a replacement for a full-fledged tutorial, but perhaps a good opportunity to explain basics and invite hands-on experimentation. 

The current welcome text is here:
https://github.com/pelagios/recogito2/blob/master/conf/onboarding/welcome.txt

Comments and suggestions for improvement appreciated!

**Comment by rsimon** [comment]
Created a skeleton for a "10 minute tutorial" (along the same lines as the old tutorial for Recogito 1 - but preferably more compact) here: http://recogito.pelagios.org/help

Contributions welcome!
