### ISSUE TITLE
Food for search engines

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#192]
We should revisit the wording we use on the splash page, in order to be easily discoverable on Google et al. E.g the splash page mentions Linked Data and annotation, but not the (digital) humanities. We need to think about what our potential users, when still unaware of Recogito, would likely search for, and make sure they'll come across Recogito then.

**Comment by rsimon** [comment]
Made an (absolute minimal) stab at this. Let's see whether/how Google sitelinks change, for example. Either way, this needs to be rethought, anyway, with the redesign of the splash page/personal index pages later this year. Closing for now.

**Comment by Addaci** [comment]
What are the current Google Analytical stats for Pelagios/Reogito and what do the data tell us about core vs casual users vs annotators?
