### ISSUE TITLE
UI features for adding multiple transcriptions

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#220]
In terms of data model & backend, having multiple alternative transcriptions is perfectly possible. However the editor popup doesn't have the user options for adding further transcriptions yet.

**Comment by rsimon** [comment]
Starting this now, but will keep it behind a feature toggle for the time being.

**Comment by rsimon** [comment]
This is now implemented. Pretty hacky and with no decent UI, but operational & behind a feature toggle, so we can try things out & potentially move to a production feature later on.

**Comment by Addaci** [comment]
Could you provide some text explanation of this feature here, or alternatively show me how to view this enhancement?

Is the idea an alternative trancription of a specific place name, or an alternative transcription of a full page [for example the Folger Library's Early Modern Manuscripts Online (EMMO) has a rather rigorous, if in my opinion over-the-top, system of providing three transcriptions for one manuscript image - full diplomatic; semi-diplomatic; modernised. See: (1) https://folgerpedia.folger.edu/Early_Modern_Manuscripts_Online_(EMMO) (2) https://emmo.folger.edu/view/La2/semidiplomatic#1r

**Comment by rsimon** [comment]
Hi,

yes, it's meant for alternative transcriptions for a specific place name (or any other label - since Recogito isn't strictly for maps, of course). Regarding full-page transcription: although that's also possible technically, of course, it hasn't been the primary use case; and other tools' UIs are better geared for this. (FromThePage for example.)

The feature is done now. But since it's more of an expert feature, and will now go into testing, it's currently behind a feature toggle. (Meaning that we can switch it on or off for specific users who ask for it.) It looks like this:

![multitranscription](https://user-images.githubusercontent.com/470971/38244147-fc0b099e-3739-11e8-913f-ab85e215e0c1.png)

I.e. you can simply add several alternative transcriptions, rather than just one. Optionally, you can attach a small note to each transcription. The original use case is one of our partners who's transcribing a specific map, but at the same time wants to record (different/disputed) transcriptions originating from other historians who have worked with the same map (decades ago.)

**Comment by rsimon** [comment]
P.S.: let me know if you want to try it out yourself and I can switch the feature on for you. (I only need to know your Recogito username.)

**Comment by Addaci** [comment]
recogito user name is *MarineLives*

*Yes, I would like to give it a quick try*

**Comment by rsimon** [comment]
Ok, should be activated for your user. Might take up to 10 minutes to become active. Cheers, R
