### ISSUE TITLE
Annotation code for OL3

### ISSUE THREAD

**Issue by klokan** [pelagios/recogito2#227]
@rsimon is it possible to reuse the annotation from this project in a plain OL3 project?

I mean the click & drag code for highlighting the area like in:

![screen shot 2016-09-02 at 18 34 16](https://cloud.githubusercontent.com/assets/59284/18211058/ee282a5c-713b-11e6-9e95-b636154520f7.png)

Where to find the code in this repo?

**Comment by rsimon** [comment]
Of course! General location of the client-side code for image annotation is here:
https://github.com/pelagios/recogito2/tree/master/app/assets/javascripts/document/annotation/image

Specifically, the drawing code for our "tilted box" selection tool is here:
https://github.com/pelagios/recogito2/tree/master/app/assets/javascripts/document/annotation/image/selection/layers/toponym

It's split in two parts: an OL3 tile image layer for rendering the existing boxes, and a separate canvas element that sits on top of the OL element. This separate canvas is where the drawing happens, and it's toggled on and off (display=none/auto) as needed.

I'm planning to make it touch compatible in the first instance (tapping would render a complete box with default length/height and two handles to adjust length/angle and heigt). Next step would be to make the shape generally editable after it was created.

**Comment by rsimon** [comment]
PS: rectangle/polygon selection will also come, but (just like with point selection) we'll just use OL3's default shape drawing tools.
