### ISSUE TITLE
HTTP responses break after ~2.6MB

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#255]
Something seems to clip the response body when it reaches a certain size. I observed this with the JSON response for all of Brady Kiesling's annotations on Pausanias. (Arguably, this is by far the biggest dataset we've seen so far, with 11,000 annotations in a single document.)

This doesn't seem to happen on the Dev setup, so might be the frontend Proxy rather than the application itself. I've "resolved" the issue now by GZIPping all JSON responses. (This brings the Pausanias dataset to around 700k.) But, obviously, that doesn't address the actual cause.

**Comment by efi** [comment]
Are you using nginx as a proxy? I once ran into this issue, when the buffer is exhausted and a temp file is written: http://serverfault.com/a/583505

**Comment by rsimon** [comment]
Hm. Sounds similar indeed. I'm using Lighttpd though. Couldn't find a ref to a buffer location. Only a few people posting a similar problem, but no answers that worked so far...

**Comment by efi** [comment]
Ah, OK. Could have seen this in the response headers... So you channel everything through mod_proxy? Then maybe `proxy.debug` (https://redmine.lighttpd.net/projects/1/wiki/Docs_ModProxy) could help tracking down the issue.

I somehow was never really satisfied with Lighttpd. If you should be ultimately seeking for an alternative, be sure to check out http://www.haproxy.org/

**Comment by rsimon** [comment]
Thx, I'll try the proxy.debug param. (In the current logs, there's no trace of anything...) In fact I was thinking about switching to nginx. But will look into haproxy!
