### ISSUE TITLE
Transfering ownership

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#259]
We need a mechanism to transfer ownership of a doc. Following (true) story: I have documents in my space which I uploaded as a demo to show to others. I gave admin permissions to them, and now they've started to happily invite new collaborators, and they made lots of annotations. Personally, I'd like to get rid of that doc in my workspace, but obviously don't want to destroy the work that others have done.

In theory, I can download a backup from te settings page, axe the doc, and hand the backup to someone else to restore. But it would still be nice to have a nice, one-click transfer mechanism. (There would probably need to be some notification mechanism, and some option to accept/reject a transfer, i.e. this might get complicated. But anyway.)

**Comment by efi** [comment]
What about a lightweight github-like forking mechanism?

**Comment by rsimon** [comment]
hm... ideally, yes that would be cool. might probably end up being a bigger task, but a good model. however, I think we'd still need to implement ownership change somehow. If we consider "normal sharing" = giving commit rights on a repo vs. forking someone's document, then I still might want to get rid of my original repo. Deleting it wouldn't affect those who forked, but those with commit rights on my repo.

**Comment by rsimon** [comment]
Ownership transfer won't be implemented. Only forking (which basically works already - but requires a bit more polishing).
