### ISSUE TITLE
Adding tags

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#262]
At the moment the tagging feature doesn't work, which means we're using the place feature to annotate all spatial entities. Were the tagging feature to have been working, I'm not sure we would have done this: nevertheless, it would be useful to capture *both* the spatial idea of the item being annotated (which is what we've been doing) *and* the type of item it is (e.g. whether it's a physical feature, or human construction). Would it be possible to "double" annotate them?

If not, would it be possible to georesolve tags?

**Comment by rsimon** [comment]
The tagging feature doesn't exist yet. (It's pretty high up on the priority list though. In terms of feature additions, focus is now on IIIF support, then tagging is next.) Yes, its possible to add georesolution, tags and comments (as many as you want, in each case, in fact).

**Comment by rsimon** [comment]
Note: if this answers the question, please close the issue. Tagging feature as such is covered already in issue #9.
