### ISSUE TITLE
escaping ; in csv export

### ISSUE THREAD

**Issue by efi** [pelagios/recogito2#269]
At the moment an annotation of a string that contains a literal `;` is put into the csv download as-is. That leads to scrambled columns when parsing the line. Some more sophisticated escaping (nesting values in `"..."`s, escaping `"` with `\"` and `\` with `\\` and so on) is needed.

Best way to use a ready-made and robust library that handles this on its own - just too much headache involved.

**Comment by rsimon** [comment]
CSV serialization now handled via [kantan.csv](https://nrinaudo.github.io/kantan.csv/) - 1f5d80360de38953c5d3674c7a32a52e4c1a47fc

**Comment by rsimon** [comment]
P.S.: kantan seems to wrap cells in `"` as soon as the separation character appears in the cell. Hope that this works @efi. Otherwise I'll look into ways of tweaking the behavior.

**Comment by efi** [comment]
Thanks! That's exactly the expected behavior. I just tested it and it works fine! The issue can be closed.
