### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#287]
Do/can tags show up in real time? I'm currently tagging annotations, and I'd like to check what tags I've been using for sake of consistency, but they don't show up.

**Comment by rsimon** [comment]
I'm not sure what you mean by "do they show up in realtime"? If you type a tag and hit enter, it should be added to the list immediately (and will get permanently stored in the annotation once you hit OK). 

If you are referring to a dropdown list of tags that you've used before: no, that's not implemented yet.

**Comment by eltonteb** [comment]
ok, no problem. Two quick follow up questions:
1. I can tag an element without identifying it as a place, right? But can I then georesolve it? (e.g. I know that the "promontory" mentioned is Sunion, and would like to map that, but I don't want to identify it as a place since the author hasn't used the toponym.)
2. Can you delete a tag? (The use case relates to a word that wasn't first identified as a place.)

**Comment by rsimon** [comment]
- Yes, all parts of an annotation are completely independent from each other. You can add tags without identifying it as a place

- No, you can not add a gazetteer reference, while at the same time saying that it is not a place (but should be mapped nonetheless). If you to indicate that something represents stuff that has a physical, mappable location in the real world, but differs from the other things you have mapped, you can use tags. Eventually, it will be possible to use tags for map symbolization. 

- Yes you can delete a tag. Click on it to see how :-)

**Comment by eltonteb** [comment]
Thanks, done!
So, just to confirm: if I want to map a feature (and georesolve it), I should mark it as a place first and foremost, and then use tags to differentiate it?

**Comment by eltonteb** [comment]
ok, so this is the schema I'm currently working to. Does it look sensible?

If there is some kind of spatial entity (even if it lacks a toponym), use the “places” marker to identify it. Then use the “tags” marker to identify any other features:
First, genus: (i) physical; (ii) human; (iii) region;
Then, type: (i) e.g. river, sea, etc.; (ii) e.g. settlement; people(s); (iii) e.g. continents, demes; 
Then use: e.g. religion; commerce; military

If it is possible to identify the location of the spatial entity (e.g. by supplying the toponym with which it is associated), georesolve it by matching it to a gazetteer.

**Comment by eltonteb** [comment]
another thought: I'm currently using tags to provide enriched information about spatial entities ("places"). But I would also like to mark (i) focalisation (where spatial information is ascribed to a particular person(s) in the text; and (ii) temporal periods (as I've mentioned before). But this raises two potential issues:
1. A conceptual issue: if I were to use tags to mark these two features as well, it seems to me there is a category confusion in how we're using tagging (enriching spatial information on the one hand, identifying whole passages that are seen from a different perspective or are set in a different time period on the other).
2. A practical issue: in practice it would mean "going over" other tags (i.e. the platial tags would be embedded within these broader tags). Can that work?

**Comment by rsimon** [comment]
So you want to annotate a (shorter) segment of text, which is *inside* a longer segment (e.g. paragraph) that is already annotated? In a printed book, you'd just create another mark/highlight on top of it, right? Why don't you just do the same in Recogito? It doesn't have to be so complicated that we need to "embed tags in other tags".

**Comment by eltonteb** [comment]
It's the reverse actually (marking a longer section of text that already has annotations - to indicate that they're in someone else's voice). That's also ok?

**Comment by rsimon** [comment]
You're not using tagging to enrich spatial information - you're just adding an extra keyword to a piece of highligted text to give some extra context, based on a vocabulary that you define. Beyond that, it's a matter of practices/guidelines that we can discuss within the community (Commons forum?) In some instances, they may make sense for a wider group of people (so a common approach is good). In other cases, they may only make sense for your own specific use case. That's why I think it would be wrong to codify any too fine-grained practices beforehand in the UI. (Also - as always - it's also a matter of lack of resources...)

**Comment by rsimon** [comment]
Annotations can overlap in whatever way you want - just try it out ;-)

**Comment by rsimon** [comment]
Concerning the schema: as I said, none of this will go into Recogito. It's up to you to use whatever vocab you want, with or without coordinating with your peers & community. Recogito won't pose a limit or enforce a vocabulary. The dropdown feature that's coming will simply make it easier to re-use tags you've already used before. It won't be fed from a common "vocabulary pool" someone dictates or defines, nor will Recogito become a taxonomy management tool. (Althoug, who knows, it could be interesting to interface with a third party taxonomy manager through a plugin?)

**Comment by eltonteb** [comment]
I was just curious of your opinion, that's all. :)

I'm still wondering about what to do about identifying relationships. I take Thomas's point about (automated) collocation being very rough and ready (given the arbitrariness of it). But I'm really talking about the user (me) being able to "tag" relations between two or more spatial entities. I realise this isn't linked data, but it would be useful for getting a sense of the internal infrastructure of a text. What place is related to what other place(s), how often, etc.

**Comment by ChiaraPalladino** [comment]
the problem is still not having any sort of authoritative reference for relationships between places. it's surprising that we have simple ontologies for personal relationships where persons lack of exhaustive gazetteer references, but not for place names, where gazetteers and authority lists are actually there. there is currently no suitable solution to make the annotation of place relationships more standardized, not only in Recogito but in general - therefore, there is no way of making those data general or usable for third parties. As you say, it's not linked data... 

+1 for @rsimon 's suggestion of an integration with external taxonomy managers - do you have anything in mind?

**Comment by rsimon** [comment]
> do you have anything in mind?

Nope :-) The only thing I know is called PoolParty. It's actually developed by a company right around the corner here in Vienna. But unfortunately not Open Source. Happy to hear suggestions though. If you know any existing tools, perhaps even worth starting a thread on the Commons forum?
