### ISSUE TITLE
Tags - automatic completion

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#296]
Would it be possible to have automatic completion of tags that were previously defined by the user? That would be a very useful feature too.

**Comment by rsimon** [comment]
Yes planned! But, indeed, I think there was no issue for this yet. Thx!

**Comment by rsimon** [comment]
- [ ] re-style tag input from editable DIV to input[type=text]
- [ ] attach typeahead.js
- [ ] editor CSS currently has `overflow` set to `hidden` so that rounded corner are clipped off. This 
      also clips off the typeahead dropdown - find a solution
- [ ] the editor doesn't currently have access to all annotations on the page. How can we get an always
      up to date list of distinct tags on this page? Without ending up with spaghetti code?

**Comment by rsimon** [comment]
Re-opening this. Some restructuring work has been going on with regard to support for dynamic color schemes in the map view. This, now, requires a bit of cleanup work on the `annotationView` class (which also drives the tag autosuggestions.

Also, there's a small typeahead glitch when a tag is entered using Tab+Enter.

**Comment by rsimon** [comment]
Typeahead glitch is now fixed.
