### ISSUE TITLE
Personal start page: list sorting options

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#301]

**Comment by efi** [comment]
The sort header would look more beautiful if you added `font-family: "FontAwesome";`to https://github.com/pelagios/recogito2/blob/67a75a59737cf02415e2dc728e64b38b93aea864/app/assets/stylesheets/my/_documentlist.less#L46 ;-)

**Comment by rsimon** [comment]
Argh - yes, thanks for pointing it out. (Weirdly enough, on my Linux machine, Chromium displayed it fine so I didn't notice. Observed this several times before. Apparently, Chromium automatically picks a different font if the default one doesn't have a glyph for the given char code. Well intentioned, I guess, but sort of annoying.)

**Comment by efi** [comment]
Wow, that's nasty - at least for developers.
