### ISSUE TITLE
Registration of IIIF source

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#32]
Add option to register an IIIF image in the document import wizard. We'll support registering an image, through the [Image Information URL](http://iiif.io/api/image/2.0/#information-request). To display the image we'll use the [KlokanTech IIIFViewer](https://github.com/klokantech/iiifviewer) as drop-in replacement for OpenLayers 3. The rest of the setup should remain compatible with what we have.

**Comment by bencomp** [comment]
How do I "register" a IIIF source then? I can only upload files from my local machine, not enter URLs.

**Comment by rsimon** [comment]
Still very much in demo stage. You can drag a link to an image info.json into the drag-and-drop area.
