### ISSUE TITLE
Import window is stuck when uploading a document

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#362]
When uploading a document in Recogito, for some reason the window showing "processing" doesn't update when the process is done. I can see my document if I reload my page (so the import actually works), but I cannot confirm the upload with the "Done" button. 

Update: I just realized it does that with large documents only. Still it's strange because the upload and import is actually performed, while the window remains stuck several minutes.

**Comment by rsimon** [comment]
Grrr... one of the December updates was supposed to fix this. I assume your freeze happened with NER enabled? NER _can_ take a long time if the texts are long. But several minutes sounds too much I agree. 

Can you E-Mail me the text it happended with? I couldn't reproduce it with my own sample (17 books of Strabo, so should qualify as large...). But, then, I [couldn't reliably reproduce it before either](https://en.wikipedia.org/wiki/Heisenbug)...

**Comment by ChiaraPalladino** [comment]
Damn - now it seems to work, and pretty quickly too O.o Maybe it was just my problem. I switched the wifi network this morning, maybe the previous one wasn't so fast.

**Comment by rsimon** [comment]
Hm. But it got stuck during the NER stage? Data transfer during that phase is minimal (the UI just polls for small status report data snippets), so Wifi speed shouldn't really matter. Maybe if the Wifi is unstable and the browser loses connection during one of the polls... need to check whether that could cause the polling to stop.

**Comment by ChiaraPalladino** [comment]
this is the window that gets frozen: 
![image](https://cloud.githubusercontent.com/assets/15249889/22154050/f7b950e4-def7-11e6-80f2-5a209b8e612c.png)

I just realized the very weird thing - it doesn't get stuck on my personal account, but it _does_  still freeze on the new sunoikisis account that I created just yesterday. It's the same texts that I have been trying and they're not even that large - it's one book from Pausanias, e.g. 

The details of the account are: 
Username sunoikisis.leipzig@gmail.com 
pw sunoikisisdc

**Comment by rsimon** [comment]
I usually encourage people not to post their passwords on Github ;-) I don't think it will be linked to the account, but I'll check for that user specifically. Can you E-Mail me the file?

**Comment by rsimon** [comment]
Things look like there was no crashed NER process. The way the progress querying is implemented since that December update is actually pretty trivial, so there's not _too_ much that can go wrong on the server-side. (Which is always a dangerous sentence to say... ;-) So I'm still suspecting something entirely browser-side...

**Comment by rsimon** [comment]
Ok, wait. I tried myself on the Sunoikisis account and can see a cause! Can't explain it yet. But at least now we nailed the bug down. Must have something to do with switching back and forth between accounts. (The progress query is rejected as an unauthorized request.) Until when do you need this stuff working?

**Comment by ChiaraPalladino** [comment]
If it has just to do with switching account then I don't have a problem - that account is supposed to be used by Sunoikisis students, and I expect that very few of them will use it to upload their own files. Also I suppose that none of them will have a previous personal account on Recogito, so they shouldn't have a problem there. 

Glad we got the bug though!

**Comment by rsimon** [comment]
Ah - nothing to do with switching accounts at all. Way more embarassing ;-) It was the mixed-case username and a small forgotten bug. This should now be resolved (commit 9cce79f9bc7353006c08f754682fdceb7749c2f1).
