### ISSUE TITLE
Recogito right now widget

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#397]
A small widget on the splash page that displays minimal activity stats:
- no. of total annotations
- no. of edits today
- no. of total users
- maybe time since last edit?

**Comment by ChiaraPalladino** [comment]
Thanks! That was what I meant.

**Comment by ChiaraPalladino** [comment]
I know it's more complicated, but is it possible to see the texts that people are working on? It's important to get an idea of what is being annotated as well (also to avoid duplicates). That could be perhaps limited to the sources that have been authorized as public by the users.

**Comment by rsimon** [comment]
There's no Github issue for that. As you say, it's somewhat complicated. Not so much in terms of the backend querying (us as application admins can see it already ;-) But the way we integrate this into the UI and workflow.

However, that's covered in our planned project extension - in terms of a "discovery mechanism will point out similar documents in the system", as well as with regard to the forking mechanim that would allow you to create a copy of someone else's (open) document, create your own derivative and then - optionally - offer changes back to the original source.

**Comment by ChiaraPalladino** [comment]
Amazing. Thanks :)
