### ISSUE TITLE
Data limit for Image upload?

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#405]
I have been trying to upload a decent-quality image of a map I'd like to annotate, but the only usable image that I have is of 15 mb. But Recogito seems to have a data limit for images that's significantly lower. 

Can we solve this issue somehow? After all, a user has 200 mb of space - I should be able to use them however I want :)

**Comment by rsimon** [comment]
That's weird. Not sure if something has gone wrong with the server config. Can you forward me the exact rejection message you are getting? In principle, the limit for individual files should be at 500MB (for our power users ;-). So if you still have space sufficient space left in your quota, a 15MB file should always go through.

Either way, I'll investigate. But I'm already at the airport, so may not be able to track this down until I find WiFi again in Leipzig ;-)

**Comment by ChiaraPalladino** [comment]
yup ;) 

I actually get no error message in the upload stage. The little box at the end of the upload has a red X instead of the usual green mark.

![image](https://user-images.githubusercontent.com/15249889/28072445-5351bc10-6653-11e7-825f-990ecd501fc8.png)

If I click on "Done", and then try to open my file, I get this error: 

![image](https://user-images.githubusercontent.com/15249889/28072479-6e406a1c-6653-11e7-864c-452a4e302e27.png)

**Comment by rsimon** [comment]
Ah that's very wird. So the previous page (upload step 2) looks OK? It doesn't look like the size limit then. Rather it looks as if the tiling process, which converts the JPEG to a zoomable image, crashes at some point, for some reason.

Can you share the file with me somehow? (Might be too big for E-Mail... Dropbox perhaps?)

**Comment by ChiaraPalladino** [comment]
Yes, everything in the process seems okay until I get to the final step. 

You can actually download the image from here: https://www.loc.gov/resource/g6810.ct001164/ 

Choose the last option (JPEG2000) and it will download it in HQ.

**Comment by rsimon** [comment]
Hm that's weird.

- Recogito will (currently) not accept files in JPEG2000 format. (But I agree it's an option worth supporting in the future.)
- Normally, Recogito should reject the JPEG2000 file based on the extension .jp2.
- I tried downloading the JPEG option and that seemed to import just fine. (But that's also a low-res copy, so not very suitable for annotating in Recogito)

Could you try downloading the TIFF option and see how it goes? I'd try it myself, but 420MB seems a bit hefty for my current airport WiFi connection. (Expect a free upgrade of your account to 1GB storage space in about 10min :-)

**Comment by efi** [comment]
Without the roundtrip over humongous TIFF files you could try uploading your jp2 here: https://convertio.co/de/jp2-jpg/ and thereby converting it to normal jpeg before uploading the resultng file to rcogito.

**Comment by ChiaraPalladino** [comment]
Thanks @efi I didn't think about that!! It worked and I was able to upload it 🥇 

Rainer, do you want me to try with the TIFF as well? I'll take the 1GB upgrade anyway :P

**Comment by ChiaraPalladino** [comment]
And I found my native city on the map. This is a reward :D 

![image](https://user-images.githubusercontent.com/15249889/28076364-c502e7b6-665e-11e7-9a8b-ed287ede8871.png)

**Comment by ChiaraPalladino** [comment]
Yup, it works with bigger documents in TIFF format. 

![image](https://user-images.githubusercontent.com/15249889/28124721-cabf08d0-6724-11e7-8858-55a01018c6ae.png)
