### ISSUE TITLE
Options for georesolution

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#408]
In Recogito v1, options for georesolution used to appear according to what had previously been annotated. For a new selection, it would be helpful if Recogito could automatically suggest a/the previous confirmed match, instead of the normal match (which is based on a string search against the gazetteer).

**Comment by rsimon** [comment]
Hi @eltonteb,

that's now implemented according to the following rules: when a new toponym is selected (by marking the text and clicking __Place__), Recogito will search existing annotations __on this page__ which...

- annotate the same toponym
- are in __VERIFIED__ status

The URIs returned from that search are sorted by their timestamp. In other words, Recogito picks the most recent verified match on the same toponym in this document as a suggestion to the user. If nothing is found this way, Recogito resorts back to a gazetteer search as normal.
