### ISSUE TITLE
Checking the textual context when georesolving

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#409]
Sometimes I’d like to see the text when making the georesolution to check on context: is there a way of minimizing the georesolution window and/or moving it around? Or is it possible to "see" the other places georesolved in the immediate preceding sequence (as one could in v1)?

**Comment by rsimon** [comment]
Georesolution panel now draggable. Feature request for displaying "nearby" georesolutions is already recorded in #294, so closing this issue.
