### ISSUE TITLE
Cursor in the search box

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#411]
When you go into the georesolution screen, can the cursor be ready in the search box?

**Comment by rsimon** [comment]
Normally, the search box will be pre-filled with the current text selection, and a first search will have been triggered with that string. You mean you'd just want the cursor positioned at the end of the current search query, so you can immediately hit e.g. DEL (or Ctrl+A and DEL) to type in a new query?

**Comment by eltonteb** [comment]
yes!
