### ISSUE TITLE
'Hide annotations' toggle

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#43]
As noted by Pau and Günther: we need a 'Hide Annotations' quick toggle to remove all annotations from the view.

**Comment by Addaci** [comment]
Is this feature now available, or hidden behind a toggle switch? Delighted you have implemented this feature - it is the first thing I thought of when trying out my first text page in Recogito https://recogito.pelagios.org/document/nmxprnlfzyeuuq/part/1/edit

**Comment by Addaci** [comment]
I am still thinking through how annotation capability in Recogito (or
alternatively in Transkribus) relates to the display and consumption of
text by human and machine users. So in answer to your question, I don't
know. It is very early days for me.

Where on Pelagios Github should I post general questions about
functionality, so I don't mess up individual worksteps?

**Comment by rsimon** [comment]
The Recogito users list: http://commons.pelagios.org/groups/recogito-users/
