### ISSUE TITLE
Starting uploading XML-cts Documents

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#437]
For now relatively short documents in Greek. 

I'll let you know how that goes ;) 

![image](https://user-images.githubusercontent.com/15249889/32109413-6c31bd1a-bb13-11e7-8ec8-949422e06a12.png)

**Comment by rsimon** [comment]
Cf. experimental CTS import feature: https://twitter.com/aboutgeo/status/1129367980922613760
