### ISSUE TITLE
tags and comments

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#443]
In the annotation screen of an annotated document is there an easy way of seeing what tags and/or comments have been made on a document? e.g. by passing the browser over an annotated entity? This would be useful when returning to a document that you had worked on in the past or that someone else has shared with you.

**Comment by rsimon** [comment]
<e.g. by passing the browser over an annotated entity?>

If you click on it? Or do you want to see things that have been added since your last visit? Or looking for a shortcut that will show more information about the whole page at a glance (colour coding etc.)?

**Comment by eltonteb** [comment]
I was thinking of a shortcut, so that I wouldn't have to click on each and every annotation to get (back) up to speed. If it's a collaborative document, yes, it would also be useful to see what had been added since my last visit.

**Comment by rsimon** [comment]
Could we cover that via alternative colour coding for example? I.e. you'd switch to a "color by tag" palette?

**Comment by rsimon** [comment]
Another case for colour coding could be by "filter by time"? I.e. to get all annotations shown that were edited after a specific date (or X days ago; since my last login, etc.)

**Comment by rsimon** [comment]
Just a quick update: there's a recent addition to the text annotation UI that might help. (It's not deployed on the production instance yet. Hopefully by end this week.) 

- It's possible to colour the annotation by tag
- The colour will be based on the first tag only. If there are more than one tags, an "indicator icon"
  underneath the annotation will show how many annotations are there in total
- Hovering the mouse over the annotation will display the list of tags (through the built-in mouseover-tooltip functionality of the browser)

I'll ping you when the change is live.

**Comment by rsimon** [comment]
That's live now! Cheers,
R
