### ISSUE TITLE
'Currently in use' warning

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#45]
Should we display a warning in text/image-annotation mode if a document has been under editing by a different user in the last X minute? We won’t be able to add Google-Drive-like live collaboration. This would at least a reasonable precaution to avoid interference between concurrent users.

**Comment by rsimon** [comment]
Just pinging @eltonteb: would this help as a workaround, since we're not going to be able to implement realtime collaboration any time soon?

**Comment by eltonteb** [comment]
yes, absolutely. I meant to ping you about it earlier, during my rash of requests earlier... Perhaps it can show up when you're looking at the documents in your user space, as a warning before you enter the document? Or should it even be "locked", if it's is already in use? (That way the onus is on the users to communicate with each other.)

**Comment by rsimon** [comment]
Yes good point about showin up on the start page already. In principle, you'll see it in the "Last edit" column (once that's implemented). But probably makes sense to have extra visual indication when last edit is < some time interval. (And it shoul probably show who made the last edit.) Not sure about locking though. You could still arrange to work on diff parts I guess.

**Comment by rsimon** [comment]
For the initial release (Dec), we'll limit the scope of this to an indication on the frontpage.
