### ISSUE TITLE
Extension point for annotation stats plugins

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#466]
At least some rough 1st draft framework for this

**Comment by rsimon** [comment]
CC-ing @thegsi: don't know if visualizations on annotation stats are interesting for you? But it could turn into some interesting frontend/JS work.

**Comment by thegsi** [comment]
@rsimon  yes, keep me updated

**Comment by rsimon** [comment]
I know have a rough plan of how I could imagine this to work. Client-side plugins that provide additional UI functionality could be bundled as ZIP files, containing

- a small metadata file, e.g. `plugin.conf` holding plugin title, the extension point where the plugin plugs in, JS and CSS source code.
- Based on the metadata, Recogito would deploy JS and CSS to the public Web resources folder
- When a page loads that has an extension point, Recogito would (again based on the metadata) link JS and CSS into that page, and create a screen area (i.e. a container `<div>`), with the plugin title.

For the time being, we could leave server-side extensions aside. I.e. the plugin would need to work with Recogito's "normal" JSON API (which we can extend as needed; and which, obviously, needs documenting).

**Comment by rsimon** [comment]
Basics (parsing of `plugin.conf` and injection into stats page) are implemented. We can follow up on a concrete example implementation as soon as there is demand/an idea for a first plugin. Meanwhile, I'm closing the issue, since nuts and bolts are in place.
