### ISSUE TITLE
Annotation Stratification

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#467]
Cf. discussion #465. Find a solution. IMO

- Stratification should be prevented altogether. I.e. the UI should not allow two annotations on the extact same text segment. (Partial overlaps yes, but not exact overlaps.) Instead, selecting an already annotated segment should open the existing annotation. The user can then add bodies (place, comments, tags,...) 
- Note that stratification __can__ still happen as a result of concurrency, i.e. if two different users each annotate the same segment at roughly the same time. We could...
  - resolve this on the server: e.g. return an error message to the user who was second, or
  - simply allow it
- Either way, we need the UI to support (and provide an extra hint) when stratification exists. 
  (Obviously, in case we choose to allow it in case of concurrency; but also because of stratification that
  exists presently in the system.)

**Comment by eltonteb** [comment]
Hi Rainer, at the impromptu Recogito workshop at the Swedish Institute last week, there was a general consensus that it would be useful to be able to make overlapping annotations. So far as I'm aware, you can annotate the smaller unit of the two, and then go on to make a second larger annotation, which overlaps with this previous one, but you can't do the reverse (start with the longer annotation and then try to mark an overlapping annotation within it). Is that right, or was I doing something wrong?

**Comment by rsimon** [comment]
Hi Elton, 

partially overlapping annotation are - and will remain - possible. (Also, I re-checked myself, and it doesn't matter if you start with the smaller or larger one. At least on Chrome & Firefox, things work as they should.)

The issue of this thread, however, is about two annotations which start and end at exactly the same positions. I.e. 100% overlap. Which is causing a whole bunch of problems (tech & conceptual, I think).

**Comment by eltonteb** [comment]
Thanks Rainer. Maybe it was the internet connection. I can see that it works now. 

So, this is about marking the same piece of text as e.g. both (something to do with) a place and, say, an event?

**Comment by rsimon** [comment]
No, it means you can currently draw a highlight that fully covers an existing highlight, and make it two different annotations, which then obstruct each other.

Marking a piece of text as both a place and a person, as several places, or (have multiple users) attach multiple tags comments, etc. (or all of the above together!) has always been totally possible, within in a single annotation.

**Comment by rsimon** [comment]
* Creating stratification is no longer possible, unless due to concurrency (as written above)
* If stratification exists on page load...
  - the annotation spans now properly stack (i.e. it's possible to delete annotations, from the top downwards)
  - additional underlines are drawn to make stratification clearly visible
