### ISSUE TITLE
Zoom buttons and rotation reset broken in image annotation view

### ISSUE THREAD

**Issue by efi** [pelagios/recogito2#476]
```
viewer.js:87 Uncaught TypeError: Cannot read property 'zoom' of undefined
    at S (viewer.js:87)
```

and

```
Uncaught TypeError: Cannot read property 'rotate' of undefined
    at HTMLDivElement.E (viewer.js:115)
```

**Comment by rsimon** [comment]
Thanks! Caught that yesterday, too. (I'm currently rewriting much/most of the image annotation code. I fixed the issue in the dev branch. Will still be a while until that's finished but I can port the fix over to the master branch in the meantime.)

**Comment by efi** [comment]
Oh, good to know.

As for me, I'm fine with those buttons not functioning for a while, I'm more of a scrollwheel user anyway.
