### ISSUE TITLE
"Crowdsourcing mode"

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#479]
A way to open up to documents for editing to anyone?

**Comment by ChiaraPalladino** [comment]
I'd second that! 

(i'm busy with submission these days, but i'm keeping an eye on Recogito - will get back at you with my observation at the end of this month...!)

**Comment by rsimon** [comment]
P.S.: "anyone" would, probably, be anyone with a Recogito account I assume. But at least, no specific sharing permissions would need to be set for each user.

**Comment by rsimon** [comment]
So here's the plan: we could emulate the sharing model that Google uses on GDrive documents. The current __Public Access__ settings dialog would be extended from a single checkbox to a radio button, plus a dropdown: 

---
 
__Public Access__

- [x] __Off__ - only specific people can access this document
- [ ] __Anyone with the link__ - anyone with the link can access, but the document will not be listed on your public profile page
- [ ] __Anyone on the Web__ - this document will be listed on your public profile page, and anyone on the Internet can find and access it

---

__Access:__ Anyone can view | can edit (editing requires sign-in to Recogito)

---
We can think about relaxing the sign-in requirement, I guess. But for now, that makes things a little simpler, development-wise.

**Comment by rsimon** [comment]
CC @gabrielbodard

**Comment by rsimon** [comment]
Preparatory work for this (and #254) is now done & deployed in production.
