### ISSUE TITLE
Typo: "BY ENTITY TYPE" not "BY ENITITY TYPE"

### ISSUE THREAD

**Issue by Addaci** [pelagios/recogito2#486]
Typo: "BY ENTITY TYPE" not "BY ENITITY TYPE"

See: https://recogito.pelagios.org/document/nmxprnlfzyeuuq/part/1/edit

![by_enitity_type_31032018](https://user-images.githubusercontent.com/1720483/38160960-191831c0-34be-11e8-8b74-e54644ee3222.JPG)

**Comment by rsimon** [comment]
Ah, thanks for spotting!
