### ISSUE TITLE
NER: enable PERSON annotation type

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#495]
The NER worker currently adds __Place__ annotations only, and discards the __Person__ ones. Add those as well.

**Comment by Addaci** [comment]
Are you using the Stanford NER? Have you modified it in any way. We experimented with a 2014 version of the Stanford NER in collaboartion with the University of Mannheim Informatics group: https://www.academia.edu/6551336/Dominique_Ritze_Caecilia_Zirn_Colin_Greenstreet_Kai_Eckert_Simone_Paolo_Ponzetto_Named_Entities_in_Court_The_Marine_Lives_Corpus_May_2014_

**Comment by Addaci** [comment]
What about identifying date, time or event annotations?

**Comment by rsimon** [comment]
- Yes, we are using StanfordNER in the production instance. (Recogito has a plugin framework, however, so NERs could be exchanged.)
- We haven't modified StanfordNER (or the language model) from it's English default. Happy to have people contribute enhanced models, though!

**Comment by rsimon** [comment]
StanfordNER does mark expressions such as "now" as a DATE entity. But we're not currently converting those to annotations in Recogito.
