### ISSUE TITLE
Linking text annotations via relationships: data model prototype

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#498]
Overall, we'll aim to keep this as minimal as possible, since there are practially no clear requirements at this stage. To that end, the minimal scope is now pretty clear. For quick reference, however, I'm also collecting some of the more out-of-the-ordinary points (which we may or may not take on board) from previous conversations (such as #299):

- "the ability to give a label to each relation and eventually attached a value to it"
- something I'd call "breaking a sentence down to triples": https://github.com/pelagios/recogito2/issues/299#issuecomment-277264098 (esp. requirement from @ChiaraPalladino)

And a [comment from Damien](http://commons.pelagios.org/groups/recogito-users/forum/topic/connected-annotations-and-multiple-possibilities/#post-1348):

> I’m not clear how these connected annotations would work when exported. What would happen if strangers, unaware of the connected annotations, exported the data to build a route? Worst case = everything would appear as they expected, and they remain blissfully ignorant of the connections. Best case = the route looks like a bowl of spaghetti and they realise that something is wrong, though without knowing why.[in response to Rainer’s suggestion] So ‘showing up in one bucket’ might be the solution. Presumably, whatever it is, it will have to work within both Recogito and the export formats. That is, a flashing exclamation mark is easy enough in Recogito but it won’t work in the export file. 

This comment, I think, relates to the question of whether a relation should be modeled as a a separate annotation ("annotating" two - or more - entity annotations); or wether the links should be kept as additional bodies to the entity annotations. (Pros and cons to both.)

**Comment by Addaci** [comment]
Still digesting the lengthy conversation in  #299 you reference above, so forgive me if this is already answered

If we go ahead and create an Early Modern Maritime Gazetteer, will there be functionality within Recogito for a hierachy of geoplaces, e.g. street within a parish within a town within a county within a country?

**Comment by rsimon** [comment]
Hi @Addaci,

I'm afraid this thread is entirely unrelated to what you are referring to. Please refer to 

https://github.com/pelagios/pelagios-cookbook/wiki/Pelagios-Gazetteer-Interconnection-Format

for questions on how place metadata can be exported from a gazetteer to be Recogito-compatible (e.g. use of the isPartOf relatio), or the LinkedPasts WG for questions on gazetteer data models and interchange formats in general: e.g. https://github.com/LinkedPasts/lp-network/tree/master/PGIFv2 

(Also, keep in mind neither Recogito, nor Pelagiosm nor any interchange format will put any restrictions on how you model your gazetteer internally. So, of course you can have hierarchical relations.)

**Comment by rsimon** [comment]
I'm currently leaning towards attaching relations to their source annotation, but model them as a separate list of bodies (which are structured in a slightly differnent way from annotation bodies). This may make storage/retrieval a bit easier. Making a stab at this in the first prototype.

**Comment by rsimon** [comment]
The first draft now models relations as a list, attached to the source annotation. Each relation contains...

- the ID of the "destination annotation"
- for future use: a list of IDs for context (triple use case)
- a list of relation bodies (nested objects, so we can compute stats over them)

Each relation body contains...
- `last_modified_by`/`last_modified_at` info
- `value`
