### ISSUE TITLE
CSV order and parts

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#568]
When exporting to CSV, annotations are currently unordered. That should be changed. (Although it's not a huge issue.) A bigger issue, however, is that the CSV currently doesn't include the filepart info. That means it's not possible to tell apart which annotations are from which file, in case the document has multiple files. Somewhat interesting that no-one has explained about this yet. But, anyways, not difficult to fix.

**Comment by ChiaraPalladino** [comment]
Sorry to reopen this, but I am experiencing the problem of unordered annotations with files imported from TEI XML. I am not sure about the filepart since i've been dealing with small texts so far.
