### ISSUE TITLE
Linked box?

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#583]
I may have lost something in the new transition, but what is the purpose of the Linked box in the image annotation?

**Comment by rsimon** [comment]
The Linked Box is a "hybrid" between the point and the Tilted Box selection tool. Admittedly, it has a __very__ specific use case, which is for map annotation:

![image](https://user-images.githubusercontent.com/470971/47984581-4ed56b00-e0d7-11e8-82d8-d2396699934d.png)

There's a frequent requirement for marking a position on a map (like a marker or symbol), plus the toponym that belongs to that marker. In many ways I think it would be more desirable to work with our normal shapes (point, rectangle, Tilted Box), and then have a way to connect or group multiple shapes. But, alas, dev time is short, and the Linked Box, frankly, was the quickest way to implement the requirement. I'm happy to hear more thoughts, though (and offers for pull requests :-D)

**Comment by ChiaraPalladino** [comment]
Oh! I see (and I agree with you, for what's worth)
