### ISSUE TITLE
TEI.2/CETEIcean upgrade

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#591]
It looks like we currently can't handle TEI.2 documents. I'm suspecting it's due to CETEIcean not properly supporting it; or at least the version of CETEIcean that we are using. Either way: an upgrade to the most recent version should be done.

**Comment by hcayless** [comment]
CETEIcean does not natively support TEI P4, but I don't see any immediate obstacles to doing so. Let me see what I can hack together.

**Comment by rsimon** [comment]
Great, many thanks! (I have to add, though: the CETEIcean version I dumped into Recogito _is_ pretty old by now, and I never updated :-( You probably made a bunch of improvements already, which we don't have on board yet.
