### ISSUE TITLE
Are the instruction for importing gazetteers still current

### ISSUE THREAD

**Issue by davanstrien** [pelagios/recogito2#619]
I'm working on the Living with Machines project and have set up a local instance of Recogito which is working but so far I haven't managed to upload a custom gazetteer.

 I might be missing something obvious but when I try and point to http://localhost:9000/admin/gazetteers as mentioned in the [documenation](https://github.com/pelagios/recogito2/wiki/Importing-Gazetteers/8313311a0b019b5e7a8bfcb189e46d2fe5810a06) I get an error. I am using the default admin user. 

Has the path for the gazetteer upload changed?

**Comment by rsimon** [comment]
While updating the Wiki page just now, I realized the page also lacks the information that Recogito now also supports (a subset of) the Linked Places data model: 

https://github.com/LinkedPasts/linked-places

It's a lot more convenient than the (slightly outdated) Pelagios RDF model. (It's JSON-LD as well as GeoJSON compatible.) I'm adding the info to the Wiki page now...
