### ISSUE TITLE
upload indicator for image and csv files

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#629]
hi Rainer,

I'm getting a glitch when uploading documents to Recogito, specifically (I think) IIIF manifests and csv. The load indicator continues to spin, making it look like Recogito is failing to upload the document; but, when I refresh the browser, the doc has indeed been uploaded.

cheers

elton

**Comment by rsimon** [comment]
Ah, yes, got it. Thanks for reporting & sorry - a regression bug after the most recent code cleanup & refactoring madness. I'll look into it.

**Comment by rsimon** [comment]
P.S.: yes, as you noticed, the upload works just fine. It's the progress UI that's broken. As soon as it says "Completed", green check marks, etc. it's safe to refresh the page.

**Comment by rsimon** [comment]
Should be fixed now!

**Comment by eltonteb** [comment]
Great. I told people it was a small bug, no problem!
