### ISSUE TITLE
Problem adding place annotations with lots of hits

### ISSUE THREAD

**Issue by hcayless** [pelagios/recogito2#633]
Ran into this testing annotations for a document. "Rhodos" got a bunch of hits, and the correct one(s) (could be the city or the island) are at the bottom of a list, and I can only access the top 5 or so. See https://www.flickr.com/photos/80806812@N00/48415006437/in/dateposted-ff/lightbox/ for a screenshot. Adding a scrollbar to the table would probably fix it.

**Comment by rsimon** [comment]
Being the person that I am (as @eltonteb will know) I have to tell you: __of course__ you can access the bottom of the list! You just need to drag the map upwards ;-) 

Nope, sorry - fully agree of course! I gave the list a maximum height now & it will scroll once that height is exceeded. (And thanks for spotting! I don't think we have many of these - rather unfortunate, actually - places, which cluster so many gazetteer records under a single node.)
