### ISSUE TITLE
"Re-Apply" option for Arabic

### ISSUE THREAD

**Issue by LabexOBVIL** [pelagios/recogito2#663]
When I use:

> Re-Apply / Show advanced options / require full word march (surrounded by whitespace, comma, etc.)

It works well for French but not for Arabic (RTL) because it annotates any string match, even inside words.
Thanks for your help.

**Comment by rsimon** [comment]
Thanks for reporting. Can you provide a suitable example I can use to reproduce the problem? Ideally, a .txt file and a word or phrase suggestion?

**Comment by LabexOBVIL** [comment]
Please find attached a sample file (or [here](https://recogito.pelagios.org/document/jhf5zkd3v56b5u/part/1/edit)) from online news. You can annotate the word فيروس (virus). The system will suggest you:

> There are 3 more un-annotated occurrences of فيروس in the text. Do you want to re-apply this annotation?

Actually, the 3 others occurences are agglutinated to prefixes:
الفيروس 
الفيروس 
بالفيروس 

Thanks for your help!
ps. you can find the same example here:

**Comment by rsimon** [comment]
Hi,

just a quick heads that I finally got a chance to look into this (and an apology for this taking so long...) I think I can publish a fix later today. Will let you know.

Cheers,
R

**Comment by rsimon** [comment]
The fix is now applied to production. Do let me know if the problem persists for you. Otherwise: happy annotating ;-)

**Comment by LabexOBVIL** [comment]
Thank you very much, it works well !
