### ISSUE TITLE
maven repository for geotools, boundless have moved?

### ISSUE THREAD

**Issue by nicolasfranck** [pelagios/recogito2#665]
These lines in https://github.com/pelagios/recogito2/blob/master/build.sbt#L22-L23
do not seem to be working anymore, as the corresponding urls are down.

I've tried to change them into:
```
"Geotools" at "https://repo.osgeo.org/repository/geotools-releases/",
"Geotoolkit" at "http://maven.geotoolkit.org",
"Boundless" at "https://repo.osgeo.org/repository/Geoserver-releases/",
```
"Geotoolkit" was necessary because "Geotools" was missing the javax.media#jai_core;1.1.3!jai_core.jar

Now it works.

**Comment by rsimon** [comment]
Ah - wonderful. Would you mind sending a pull request for this?
