### ISSUE TITLE
Tags not working in the Map view

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#673]
Is there a particular reason why the tags don't appear anymore in the color and filter settings? If I select that option in the menu, I can't even see the tags used.

**Comment by rsimon** [comment]
Hi @ChiaraPalladino,

ouch, sorry. There was recently some "improvement" work on the tags... looks like I missed one minor side effect here. I already patched the code. Should go live within the next few hours.

**Comment by ChiaraPalladino** [comment]
I think it's working now :) Thanks!
