### ISSUE TITLE
Gazetteer Disambiguation when Tagging

### ISSUE THREAD

**Issue by docuracy** [pelagios/recogito2#683]
Each authority file is assigned a colour when uploaded to Recogito, but these colours are not used to identify the source of a suggested authority when geotagging; in fact it seems to be impossible to know the origin of a suggested authority until it has been selected and its url appears.

In our use case, with sometimes multiple users working on the same multi-page document, it is not always practical to adjust the gazetteer selection in order to limit the suggestions to a specific gazetteer, because the gazetteer selection is applied per document rather than per user.

Can anyone please suggest a workaround, or even a permanent solution?

**Comment by rsimon** [comment]
Not quite sure I understand that requirement. Do you mean you have ("meta"-)gazetteers that include places from multiple URI domains and want colors based on the uterus URIs rather than per gazetteer? Or is there an extra source field you want to display?

**Comment by docuracy** [comment]
Actually, Rainer, I've just realised that hovering on the [?] icon reveals the gazetteer url. It would be handy to have that information available in the map tag popup too. Better still would be to have the Shortname of the Authority file in both the suggestion list and in the map marker popup; the Authority's assigned colour might be used for the marker.
![image](https://user-images.githubusercontent.com/42514781/109411516-93692c80-799a-11eb-941d-c74b671025ad.png)

**Comment by rsimon** [comment]
Looks like your gazetteer configuration is messed up. You need to set a shortname, and a URL pattern. This allows the UI to generate the URI preview. 

This is what the list would look like with a gazetteer colour code set (mouse hover shows the shortcode):
![image](https://user-images.githubusercontent.com/470971/109412245-28722280-79a7-11eb-9fe7-7da047630bba.png)

And this is what the map popup looks like:
![image](https://user-images.githubusercontent.com/470971/109412273-4dff2c00-79a7-11eb-9d97-eab9d2ddd6fb.png)

The URL pattern can be simply a string, in which case the Recogito will keep everything after the string as the ID. E.g.

```
http://pleiades.stoa.org/places/
```

will turn `http://pleiades.stoa.org/places/12345` to `{shortcode}:12345`, i.e. `pleiades:12345` in the UI.

Alternatively, you can use:

http://mapoflondon.uvic.ca/{{id}}.htm

To clip an identifier from inside a URL.

**Comment by docuracy** [comment]
Thank you, Rainer. Problem solved. 🙂
