### ISSUE TITLE
IIIF filename: incomplete urlencoding

### ISSUE THREAD

**Issue by docuracy** [pelagios/recogito2#690]
We hit a snag due to the incomplete urlencoding of filenames in the document_filepart table. Colons are encoded as %2F but spaces remain unencoded. In our use case this caused a problem with a PHP file_get_contents call.
 
![image](https://user-images.githubusercontent.com/42514781/112797001-af77f080-9062-11eb-8317-795f9740b25b.png)

**Comment by rsimon** [comment]
I don't think that's something that Recogito even touches. The filenames are inserted as-is, i.e. this should be the URL you originally imported to Recogito. (And how it was included in the manifest.)

**Comment by docuracy** [comment]
Oops. Thanks, that would explain it!
