### ISSUE TITLE
Options button does not work, opens empty page

### ISSUE THREAD

**Issue by AlexanderDH** [pelagios/recogito2#700]
I installed recogito locally, using the provided instructions. The tool itself seems to work well, but there seems to be an issue with the "options" button, whenever picking one document.
The issue: once I have uploaded a document (just an image for testing purposes) and I click onto it on the default page that you see upon log-in, the options button appears in the top right corner. Normally a small dropdown window would pop-up when clicking onto "options", with e.g the possibility to delete that one document. 
But: whenever I click onto it, an empty page opens and replaces the page that you see. 
The address in the browser stays the same: 131.xxx.xxx.xxx/recogito (user named recogito), it is just a blank page that you see.
Refreshing the window/tab re-opens the normal default page, with the normal default view, the list of documents, etc. and there I can reproduce the same behavior of the options button, whenever I pick any one document.
Non-admin users have the same issue. 
Other functionalities do not seem to be affected. 
Uploading gazetteers works well, too.

**Comment by rsimon** [comment]
Hi, thanks for reporting. Can you check the browser console (hitting F12 on most browsers, including Chrome & Firefox, will open it) and see if there's an error message?

**Comment by rsimon** [comment]
P.S. another question: did you install from the repository just now? Or before Nov.7? (The reason I'm asking is because there was a fix published on Nov.7 which __should__ have addressed this... But if your copy of Recogito is newer, then that probably didn't work for all cases...)

**Comment by AlexanderDH** [comment]
> Hi, thanks for reporting. Can you check the browser console (hitting F12 on most browsers, including Chrome & Firefox, will open it) and see if there's an error message?

Hi. Thanks for the quick reply! That's the error messages I get (sorry for the sloppy copypaste):

TypeError: e.account.feature_toggles is undefined
    ge Header.jsx:25
    React 7
react-dom.production.min.js:3843
Uncaught TypeError: e.account.feature_toggles is undefined
    ge Header.jsx:25
    React 7
Header.jsx:25:29

​

**Comment by AlexanderDH** [comment]
> P.S. another question: did you install from the repository just now? Or before Nov.7? (The reason I'm asking is because there was a fix published on Nov.7 which **should** have addressed this... But if your copy of Recogito is newer, then that probably didn't work for all cases...)

Thats probably it. It's older. I gitcloned it on Oct.27. 
Is there some automated update-functionality or some bit in the wiki, where it says how I can have it updated or what bit needs to be replaced (if it were that easy)? Or would I have to reinstall it?

**Comment by rsimon** [comment]
Ok, yes, that's it. It won't have the fix if you cloned before Nov 7.

> Is there some automated update-functionality

No, there's no automatic update feature. But if you cloned from the repository: a simple `git pull` and restart will do.

**Comment by AlexanderDH** [comment]
> Ok, yes, that's it. It won't have the fix if you cloned before Nov 7.
> 
> > Is there some automated update-functionality
> 
> No, there's no automatic update feature. But if you cloned from the repository: a simple `git pull` and restart will do.

Ah, thanks again! Then I'll just pull and restart.
