### ISSUE TITLE
Fuzzy option needed on georeferencing view

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#71]
That was very useful on V1

**Comment by rsimon** [comment]
Yes, another good point. Actually, geo-res search already (invisibly...) switches to fuzzy search when the normal search returns 0 results. But definitely, this needs to made explicit, and get a button.

(Note for workaround at present: fuzzy search is generally triggered by appending a ~ character to the search query. I.e. "bvrdigala" will not match to "Burdigala/Bordeaux", whereas "bvrdigala~" will. But as I said: just meant as a temporary workaround.)

**Comment by rsimon** [comment]
Update to this: in fact, search did NOT switch to fuzzy mode when zero results were found. The fix below adds this feature. I.e. exact search followed by fuzzy is now the default.
