### ISSUE TITLE
Usual Hardware configuration

### ISSUE THREAD

**Issue by josircg** [pelagios/recogito2#710]
Hi folks, 

Could you provide the regular RAM/CPU configuration to run recogito for a small number of users?

**Comment by rsimon** [comment]
Hi,

the bottleneck is usually *just* the ElasticSearch index. I've been running successfully with a single CPU and 4GB. Although for anything that involves more than a single user (and if you want to keep it running without regular restarts), I'd recommend at least 8GB RAM. In terms of CPU, even a low-end config should be sufficient. (Recogito is 4 year old software after all.) Disk space is determined by whether you want to upload (large) images. If not, a few GB will be enough. (I've had it running on 30GB, with half of that occupied by the OS.
