### ISSUE TITLE
Automatic tagging based on manual annotation

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#72]
This used to be one of the main features of V1, i.e. when you annotate one place manually and it proceeds to automatically recognize the same place in the whole document. Not sure whether it should be implemented also for other types of annotation, though.

**Comment by rsimon** [comment]
That should already be recorded as issue #47 ("Automarking of Identical Phrases"). I guess this should not only tag identical phrases as places as well, but also copy over the geo-resolution, if available? (But potentially retain status of "UNVERIFIED"?)

**Comment by ChiaraPalladino** [comment]
Yeah, I think it's the same issue actually (sorry!). I am not sure if it wouldn't just be messy to have the same feature on multiple-word toponyms or more "semantic" types of annotation (e.g. entire phrases...that would be too much perhaps). 

It would be useful if it could cover georesolution but asking for user verification like in V1. 

Also punctuation is a problem, but I wouldn't say that it needs to be removed for automatic recognition - from my point of view, it's fine not to have automarking if the entities do not overlap perfectly.

**Comment by rsimon** [comment]
No prob - that's what the issue tracking system is there for!

Hm - so you think as soon as you select a multi-word phrase and tag it a place, Recogito should not suggest identical matches?

I agree punctuation should be removed when searching for matches. The comment in issue #47 mostly relates to the Recogito 1 issue that tokenization was trivially based on white-space - a quick hack that would, e.g., not find "Athens." as a match on "Athens".

**Comment by ChiaraPalladino** [comment]
Strings marked as places should always be recognised as identical matches (as in V1), but I'm not sure about longer annotations in general. On the other hand, it is very unlikely that long strings are completely repeated in a text. It really depends on the type of task that the annotator is performing, so this is one of those things that need to be tested on use cases...

**Comment by rsimon** [comment]
Ok, makes sense. I would simply have tied it to the type of the annotation "body" (to use Open Annotation parlance): whenever you create a place "body", Recogito would search for identical phrases and create annotations there (with just the place body). 

The same I'd do for person bodies once we have them. But probably not the free-text comments. But as you say: definitely something to be tested on use cases.
