### ISSUE TITLE
Problems with place verification

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#73]
Newly verified places do not appear green in verification status view. Tried to refresh and to change view, nothing happens.

**Comment by rsimon** [comment]
They should turn green as soon as you click 'OK'. But agree they should probably turn green instantly (and then go back to grey in case of cancel)?

**Comment by rsimon** [comment]
Just pinging this issue @ChiaraPalladino. Is this still a problem?

**Comment by ChiaraPalladino** [comment]
It seems okay now. I still don't understand why the small georesolution window is repeated if you click on "place" multiple times. Here is a screenshot: 

![image](https://cloud.githubusercontent.com/assets/15249889/19470124/883ef66a-951e-11e6-9259-545ca681ba4e.png)

**Comment by rsimon** [comment]
Probably not too good looking, and needs to be better communicated (with an additional info popup, perhaps, when adding additional mappings), but is intentional.

The reason is that we want to support cases where users want to add multiple mappings to one annotation. Either because the toponym refers to multiple places ("the town and the river named..."), or people are uncertain and want to indicate multiple possible options (rather than just flag). In this case, comments could be used to discuss the context.

**Comment by ChiaraPalladino** [comment]
Oh, that's great then! Yes we'll need guidelines for that :) But does it translate into the export formats as well? It doesn't seem so to me.

**Comment by rsimon** [comment]
Yes, guidelines :-) Hm - the export formats are all work in progress. So anything other than the first gazetteer mapping in the list probably doesn't (yet!) show up there. CSV is a special case: as a tabular format, it will generally be difficult to export the whole list of places. For GeoJSON, RDF, etc. this won't be an issue, of course. I'm really mostly waiting for use cases & people to give me a shout on what format (and content) they need exported.

P.S.: did you see the nifty visualization of place co-occurrence (based on character distance) that @efi built, using the CSVs as input? http://recogito-network.textgraph.science:2224/document/xzephxecjjybkd (cf. issue #263)

**Comment by eltonteb** [comment]
Hi Rainer, can you unpack that first use case? I think that, in the scenario where the town and river, say, are mentioned as having the same toponym, I would annotate them separately with that toponym. Is that *wrong*?

**Comment by rsimon** [comment]
I'm specifically referring to text that says "the town and the river named {insert toponym here that's shared by both the river and the town", so the toponym only appears once in the text, but refers to two places. Or another case we've used as example "the four Gallias".

**Comment by eltonteb** [comment]
right. So how would that work? I annotate the toponym... and how do I show that it denotes the town and river? (I'm trying to visualise it.)

**Comment by rsimon** [comment]
You add the gazetteer URI for the river AND the gazetteer URI for the town. See the screenshot above for multiple "gazetteer sections" in a single annotation.

**Comment by efi** [comment]
Sorry, to interrupt you guys... But to make this issue super-non-linear I want wo refer to another more general multi-place-usecase again: I have until now understood it as a way of "linking" entries from different gazetteers that are "somewhat equal" in this specific annotation scenario.

Something in the lines of:
![image](https://cloud.githubusercontent.com/assets/112480/19470911/8908af0c-9521-11e6-9ee7-1ac7e6b031ae.png)

Is that "supported" in the way that both LOD entries are added to the *same* annotation or does it have to be reverse engineered by offset and string value of two annotations?

Problem is anyway in the semantics are those "AND" or "OR" connected? Does it mean both URIs refer to the same thing or there are two distinct things, each with its URI?

**Comment by rsimon** [comment]
Both URIs are (explicitely) part of the same annotation, data-model-wise. I deliberately left out any of the semantics - whether this is an AND, OR, an "Elton says this, but I think it's that", or anything else. I assume that common scenarios will emerge. But until then, I'd rather leave it as a general-purpose functionality for adding multiple URIs, and leaving it up to the collaborators (via comments or tags) to agree on a meaning amont them, on a case-by-case basis.

**Comment by rsimon** [comment]
P.S. in terms of the LOD serialization, it will be expressed as different "bodies" of the same "annotation" (in Open Annotation terminology). The same limitation applies to the OA model in general: that there is no mechanism that expresses how the different bodies are related to each other. (Or rather, this is simply considered out of scope for the model, at least as far as I'm aware.)

**Comment by efi** [comment]
Sounds reasonable! Thanks. Of course that makes it almost non-operatable for external tool providers to devise any definitive treatment. But that's OK. Specfic tools for specific use-cases - or configurable generic tools, that's it.

**Comment by rsimon** [comment]
I'm definitely not against some sort of mechanism that adds more explicit semantics. But I think it would be quite difficult to develop something, top-down, that doesn't break as soon as different people come in with different expectations and use cases. So let's better wait and see what users are doing :-)
