### ISSUE TITLE
Can we integrate entity recognition via the CLTK?

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#92]
Would give us Latin & Greek for example. It's Python though, so integration is a problem. Build a jar with Jython perhaps?

**Comment by ChiaraPalladino** [comment]
I'd be curious to see if CLTK works well in this case.

**Comment by rsimon** [comment]
An alternative/addition could also be polyglott-ner:

https://polyglot.readthedocs.io/en/latest/

**Comment by rsimon** [comment]
Technically, this is now possible since the introduction of the [NER plugin SDK](https://github.com/pelagios/recogito2-plugin-sdk). Still closing this issue here, since we won't have time & resources to develop the actual plugins as part of Pelagios Commons.
